spring:
  application:
    name: fastjee-cloud-web-admin-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

server:
  port: 8904

management:
  endpoints:
    web:
      exposure:
        include: "*"

